# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/Computer organization/MineCPU/code/vivado_project/vivado_project.srcs/sources_1/ip/progrom/progrom.xci
# IP: The module: 'progrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Computer organization/MineCPU/code/vivado_project/vivado_project.srcs/sources_1/ip/progrom/progrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'progrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/Computer organization/MineCPU/code/vivado_project/vivado_project.srcs/sources_1/ip/progrom/progrom.xci
# IP: The module: 'progrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Computer organization/MineCPU/code/vivado_project/vivado_project.srcs/sources_1/ip/progrom/progrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'progrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
